#!/bin/sh
# the category files must start with '.' otherwise environment vars
# such as DBACL_PATH are consulted
. ./share/dbacl/TREC/OPTIONS
if [ -n "$AUDITCOMMAND" ]; then 
    "$AUDITCOMMAND" train "$1" "$2"
fi
./bin/dbacl $DBACL_LOPTS -m -l ./db/$1 -o ./db/$1.onl $2 2>>stderr.log
